name: space_pod
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  convert: ^3.1.1
  lottie: ^3.1.0
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc:
  dio:
  cupertino_icons: ^1.0.6
  dart_format: ^1.1.11

dev_dependencies:

  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/animination/
    - assets/font/
    - assets/image/

  fonts:
    - family: Sixtyfour
      fonts:
        - asset: assets/font/Sixtyfour.ttf
    - family: Oregano
      fonts:
        - asset: assets/font/Oregano.ttf

